// Section: Data Source and Description

== Data Source and Description

=== Dataset Origin

The dataset analyzed in this study was generated by the *INOHAC AMR Project Two* research team as part of an environmental antimicrobial resistance surveillance initiative. The present study does not involve primary sampling or laboratory experimentation. All analyses are conducted as a *secondary analysis* of phenotypic AST data collected by the source project.
The dataset comprises AST results for bacterial isolates obtained from environmental and aquaculture-associated sources across three geographic regions in the Philippines: Eastern Visayas, Central Luzon, and the Bangsamoro Autonomous Region in Muslim Mindanao (BARMM).

=== Sample Source Categories

Isolates originate from environmental matrices representing the *Water–Fish interface* within the broader Water–Fish–Human nexus. These source categories capture exposure pathways relevant to environmental AMR dissemination and are used exclusively as contextual metadata during interpretation. Source categories are listed in @tab:sample-source-categories.

#figure(
  table(
    columns: 3,
    table.header[*Source Code*][*Source Type*][*Description*],
    [DW], [Drinking Water], [Community water sources],
    [LW], [Lake Water], [Natural water bodies],
    [RW], [River Water], [Flowing water systems],
    [EWU], [Effluent Water (Untreated)], [Hospital or facility discharge (Human interface)],
    [EWT], [Effluent Water (Treated)], [Processed effluent discharge (Human interface)],
    [FB, FG, FT, FK], [Fish], [Banak, Gusaw, Tilapia, Kaolang],
  ),
  caption: [Sample Source Categories],
) <tab:sample-source-categories>

*Note:* While direct human clinical isolates are not included, effluent water samples (EWU, EWT) represent the anthropogenic component of the nexus, capturing resistance patterns potentially influenced by human antibiotic use and healthcare facility discharge.

=== Isolate Identification Convention

Each isolate is assigned a structured alphanumeric identifier encoding species, geographic origin, source type, replicate number, and colony number using the format:

#raw(block: true, lang: none, "[Species Prefix]_[Region][Site][Source][Replicate]C[Colony]")

This convention enables systematic metadata parsing while preserving traceability throughout the analytical pipeline.

=== Antimicrobial Panel

Phenotypic AST data consists of a panel of *22 antibiotics spanning 12 antimicrobial classes*, including an ESBL screening indicator. The antimicrobial panel is summarized in @tab:antimicrobial-panel.

#figure(
  table(
    columns: 2,
    table.header[*Antimicrobial Class*][*Antibiotics*],
    [Penicillins], [Ampicillin],
    [β-lactam/β-lactamase inhibitors], [Amoxicillin/Clavulanic Acid],
    [Cephalosporins (1st gen.)], [Cefalexin, Cefalotin],
    [Cephalosporins (3rd/4th gen.)], [Cefpodoxime, Cefotaxime, Cefovecin, Ceftiofur],
    [Advanced cephalosporins], [Ceftaroline, Ceftazidime/Avibactam],
    [Carbapenems], [Imipenem],
    [Aminoglycosides], [Amikacin, Gentamicin, Neomycin],
    [Quinolones / Fluoroquinolones], [Nalidixic Acid, Enrofloxacin, Marbofloxacin, Pradofloxacin],
    [Tetracyclines], [Doxycycline, Tetracycline],
    [Nitrofurans], [Nitrofurantoin],
    [Phenicols], [Chloramphenicol],
    [Folate pathway inhibitors], [Trimethoprim/Sulfamethoxazole],
    [Resistance indicator], [ESBL screening],
  ),
  caption: [Antimicrobial Panel Composition],
) <tab:antimicrobial-panel>
